### PR TITLE
Add a new feature to let test methds in a class run as user specified order

### PR DESCRIPTION
**Pull request by JacobCN**
This is a new feature to let JUnit run as you specified order. What we need do is two steps:
1. Adding annotation 'FixMethodOrder(MethodSorters.SPECIFIED_PRIORITY)'.
2. Specify 'priority' value for methed annotation 'Test'.

This feature is an optional featue to let JUnit users specify method order in some special scenarios.
More details please refer to the comments in changed code.

### CODE REVIEW

**Comment by JacobCN** [comment]
Add a new feature for @Test, to let JUnit specify method order in one method.

**Comment by kcooney** [comment]
Thanks for the contribution.

I am hoping we could include #1130 in 4.13, which is a more general and flexible way to solve this problem. With that pull, you could create a custom`Ordering` that ordered the methods by any criteria you specify (including annotations on the method). Some users will.want to specify order via a priority, others with a unique priority, and others via some dependency.

**Comment by JacobCN** [comment]
@kcooney Thanks for your comment.

I read the code of #1130, which it is a good solution. And as a JUnit user I hope to add the order feature ASAP, cause it is really a pressing need. But I think the solution in this PR is more convenient in some scenario, especially when I could not describe the order by programming. What's more, this solution is an optional way to describe the test method order.

**Notice** This feature in this PR has the same behavior as another unit test framework **TestNG**. This is a convenient way as my experience.
  * _There is no worry about about the license conflict with TestNG License Apache 2.0. My code is from my own design and there is no any code reference to TestNG, otherwise it will not work well._

**Comment by kcooney** [comment]
I'm curious what the other maintainers think. @junit-team/junit-committers 

While adding an attribute is convenient, I would prefer we don't merge this pull for 4.13, for these reasons:

1. Some people strongly feel that tests should be independent and not depend on ordering. For those users, adding a `priority` or `order` attribute to `@Test` is too easy and therefore sends the wrong message
2. This pull relies on `@FixMethodOrder`, which was a temporary work-around for Java no longer guaranteeing the order that methods are returned from the reflection APIs
3. It's not that hard to write a custom annotation and an associated Ordering
4. We could update`@Test` later after we see how people use `Ordering`

**Comment by dsaff** [comment]
Momentarily delurking to say that I think it would be good for the JUnit design if @FixMethodOrder was used less and less, not more and more.  (Basically everything @kcooney said.)

**Comment by JacobCN** [comment]
@kcooney @dsaff , thanks for your explanations.
I think I caught the key point.  '<@FixMethodOrder>' is only a temporary work-around. @kcooney Do you mean this annotation is a deprecatory solution, or it will be removed or marked by '<@deprecated>' in the future?

**Comment by kcooney** [comment]
@JacobCN if Ordering is added in 4.12 then I will probably deprecate `@FixMethodOrder`. If past behavior is any predictor of future behavior, we won't remove it until after the thermal death of our sun.

**Comment by JacobCN** [comment]
Got it, I close this PR now.

**Pull request closed without merging**
