### PR TITLE
Add ErrorCollector.checkThrows()

### PR DESCRIPTION
**Pull request by kcooney**

### CODE REVIEW

**Comment by marcphilipp** [comment]
Nice! 👍 

I think it might be helpful if `checkThrows` returned the (expected) exception, like `Assert.expectThrows()` does. More detailed checks could then be performed using `ErrorCollector.checkThat()`. What do you think?

**Comment by kcooney** [comment]
@marcphilipp What would it return if the lambda did not throw that exception?

**Comment by marcphilipp** [comment]
Point taken.

**Comment by marcphilipp** [comment]
LGTM! Feel free to merge (and add it to the release notes). 😄

**Comment by kcooney** [comment]
Merged and added to the release notes

**Comment by marcphilipp** [comment]
Thanks!

**Pull request closed without merging**
