### PR TITLE
capture log4j logs rule

### PR DESCRIPTION
**Pull request by sapirgolan**
Adding a new rule that capture all logs that were written using log4j

### CODE REVIEW

**Comment by kcooney** [comment]
Thanks for the contribution

We generally try to avoid adding any external dependencies to JUnit. Hamcrest was an exception, and that caused all kinds of problems.

**Comment by sapirgolan** [comment]
Hi kcooney,

I'm aware of that, I read your POM and saw only a single dependency, Hamcrest.
However, This depedency has the 'optioanl' property set, meaning that users have to specify it if they want to use it - https://maven.apache.org/guides/introduction/introduction-to-optional-and-excludes-dependencies.html

If someone is already using log4J he will have the dependency in this mvn module

**Comment by Tibor17** [comment]
@sapirgolan is right.
@kcooney log4j is needed only to compile junit. One way or another, it is guaranteed that this rule is used by log4j user who already owns log4j dependency in his classpath; otherwise `ClassNotFound` is thrown. The normal user who does not use this rule would not have class loading issue. I am only facing a problem in OSGi, for instance PAX; they should exclude package but I guess log4j is used everywhere, so no issue.

**Comment by Tibor17** [comment]
hamcrest cannot be compared with log4j because hamcrest affected the everything, however log4j only this rule in the least invasive way.
@sapirgolan I am using slf4j. Can I use this rule as well?

**Comment by sapirgolan** [comment]
@Tibor17 , slf4j is abstraction for various logging frameworks, where log4j is only one of them.
When using slf4j, you need to plug in the desired logging framework at deployment time.

If you plug in log4j the rule will work. But if you plug another framework, java.util.logging for example, it will not work.

**Comment by kcooney** [comment]
Personally, I would lean against JUnit having even a compile-time dependency on a third-party logging framework. Third-party APIs change in incompatible ways.

Secondly, one of the core principles of JUnit is APIs over functionality. See "Prefer Extensions Over Features" at https://github.com/junit-team/junit-lambda/wiki/Core-Principles

**Comment by stefanbirkner** [comment]
I would like to close this pull request. It does not fit into the scope of JUnit which is the core testing framework and the base for building elaborate support for testing other library. Therefore Rules have been introduced. Everyone can create a library with rules and publish it. E.g. I have done this with [System Rules](http://stefanbirkner.github.io/system-rules/).

**Comment by marcphilipp** [comment]
I agree with @kcooney and @stefanbirkner.

**Pull request closed without merging**
