### PR TITLE
Use canonical class name for failure message in expectThrows()

### PR DESCRIPTION
**Pull request by kcooney**

### CODE REVIEW

**Comment by kcooney** [comment]
Note there are two commits, and I want to keep them separate. I'll be happy to merge once someone approves.

**Comment by marcphilipp** [comment]
There's the edge case of classes that don't have a canonical name. Can we use `getName()` as a fallback for such cases?

**Comment by kcooney** [comment]
@marcphilipp done. PTAL

**Comment by kcooney** [comment]
@marcphilipp done. https://github.com/junit-team/junit5/issues/575

**Pull request merged**
