### PR TITLE
add hamcrest-library as a test dependency

### PR DESCRIPTION
**Pull request by alb-i986**
As discussed in #1292 
(see https://github.com/junit-team/junit4/pull/1292#issuecomment-219239388)

### CODE REVIEW

**Comment by kcooney** [comment]
Do we have immediate plans to use this dependency?

**Comment by alb-i986** [comment]
I may use it here

https://github.com/junit-team/junit4/pull/1302/files#diff-5ac6ee0460714bbb4ceac9a9b91df336R39

to ensure that the signature of failureCountIs allows to take greaterThan.

**Comment by kcooney** [comment]
I realize this is personal preference and I am looking at only two data points , but I think that 69e8a8a6b3 made the tests easier to read. It is extremely rare for me to write an assertion that a given integer is greater that some value (or less than some value, or not equal to some value). 

That being said, I find Hamcrest assertions hard to read (compared with Fest or Truth) so it might be just me, so I won't object to the new dependency.

**Comment by alb-i986** [comment]
> I find Hamcrest assertions hard to read (compared with Fest or Truth) so it might be just me, so I won't object to the new dependency.

Sounds like you are not happy with hamcrest. Fair enough, but here I'm not proposing to introduce hamcrest, I'm only trying to help us contributors writing cleaner unit tests by providing more Matchers to use. It's only about giving more options, really.

Besides `greaterThan` and similar, another pretty common matcher which is missing right now is `hasSize`.

```
$ rgrep 'assertThat.*[sS]ize' src/test/java/
src/test/java/org//junit/experimental/categories/CategoryValidatorTest.java:        assertThat(errors.size(), is(1));
src/test/java/org//junit/experimental/categories/CategoryValidatorTest.java:        assertThat(errors.size(), is(0));
src/test/java/org//junit/internal/runners/ErrorReportingRunnerTest.java:        assertThat(firedFailures.size(), is(1));
src/test/java/org//junit/runners/model/TestClassTest.java:        assertThat("Wrong number of annotated fields.", annotatedFields.size(), is(3));
src/test/java/org//junit/runners/model/TestClassTest.java:        assertThat(values.size(), is(1));
src/test/java/org//junit/runners/model/TestClassTest.java:    	assertThat(values.size(), is(1));
src/test/java/org//junit/tests/experimental/max/DescriptionTest.java:        assertThat(description.getAnnotations().size(), equalTo(0));
src/test/java/org//junit/tests/experimental/max/DescriptionTest.java:        assertThat(description.getAnnotations().size(), equalTo(1));
src/test/java/org//junit/tests/experimental/max/DescriptionTest.java:        assertThat(description.getAnnotations().size(), equalTo(0));
src/test/java/org//junit/tests/experimental/theories/internal/AllMembersSupplierTest.java:        assertThat(valueSources.size(), is(2));
src/test/java/org//junit/tests/experimental/theories/internal/AllMembersSupplierTest.java:        assertThat(valueSources.size(), is(2));
src/test/java/org//junit/tests/experimental/theories/runner/SuccessfulWithDataPointFields.java:            assertThat(list.size(), is(1));
src/test/java/org//junit/tests/experimental/theories/runner/WithDataPointMethod.java:            assertThat(first.size(), is(0));
src/test/java/org//junit/validator/AnnotationsValidatorTest.java:        assertThat(errors.size(), is(1));
src/test/java/org//junit/validator/PublicClassValidatorTest.java:        assertThat("Wrong number of errors.", validationErrors.size(),
```

All of these assertions could be refactored to use `hasSize`.

**Comment by kcooney** [comment]
I'll defer to Marc on this one.

**Comment by marcphilipp** [comment]
Thanks!

**Comment by alb-i986** [comment]
Thank you @marcphilipp!

**Pull request merged**
