### PR TITLE
Revert "ExternalResource: declare after() to throw Throwable (#1421)"

### PR DESCRIPTION
**Pull request by panchenko**
This reverts commit cebbf5e15725b4dc247ac0557f6fa63f475b15af.

### CODE REVIEW

**Comment by panchenko** [comment]
@marcphilipp seems like I don;t have permissions to update wiki :(

**Comment by stefanbirkner** [comment]
I removed #1421 from the release notes.

**Comment by stefanbirkner** [comment]
@panchenko Can you please change the commit message to containt @kcooney's comment from #1421. You can copy the following commit message:

    Revert "ExternalResource: declare after() to throw Throwable (#1421)" 

    Revert commit cebbf5e. It breaks code that extends ExternalResource,
    overrides after() and calls super.after() in after().

It will help people to understand the code change later on.

**Comment by stefanbirkner** [comment]
@panchenko Thanks for updating the commit message.

**Comment by marcphilipp** [comment]
Thanks, @panchenko!

**Pull request merged**
