### PR TITLE
MethodSorter METHOD_ORDER allowing to specify the execution order of test methods

### PR DESCRIPTION
**Pull request by adamsiemion**
- added attribute order to the Test annotation for specyfing the execution order
- created a new MethodSorter (METHOD_ORDER) and added it to the MethodSorters enum
- created a unit test for this feature

### CODE REVIEW

**Comment by tobiasKaminsky** [comment]
This would be a great feature for me as it is more intuitive to have the tests executed in the same order as they are written.
Of course this only matters if the tests needs to be in a specific order.
Currently I avoid this problem by adding numbers to the front of the tests and use NAME_ORDER.

(And I know that a testsuite should work without a specific order, but in this case it is not possible :/ )

**Comment by cardil** [comment]
:+1: for this feature. BTW. Random order, just like Ruby rspec, whould be nice to!! Mayby I will do that in seperate PR

**Comment by tobiasKaminsky** [comment]
@cardil As far as I have understand and read the current sorting oder is random, but always the same for a specific computer and java machine.

**Comment by cardil** [comment]
@tobiasKaminsky Yup. hashcodes for strings doesn't change beetween JVM executions. So, the truely random order would be nice.

BTW. This discusion is offtopic :-P so I've created new issue for that: #1194

**Comment by kcooney** [comment]
There are many ways that people could want to specify the ordering of methods, so I personally would prefer that we added an extension point that allowed you to define your own class that does the ordering or sorting.

See #1130 for one way we could do that

**Comment by kcooney** [comment]
I don't support specifying an ordering in the `Test` annotation. The JUnit team has long encouraged tests to not depend on ordering. While I can see why some projects might need to specify an ordering, I don't think adding support to the `Test` annotation would encourage it too strongly.

**Pull request closed without merging**
