### PR TITLE
Outboxing issues corrected

### PR DESCRIPTION
**Pull request by Mathreyu**
Some outboxing warnings were corrected as signaled in the IDE.

### CODE REVIEW

**Comment by kcooney** [comment]
Thanks for the contribution.

I actually prefer the explicit call to the `valueOf()` methods in these cases, so i vote to not merge this.

**Comment by Mathreyu** [comment]
@kcooney I found a previous PR on which another outboxing warning was corrected https://github.com/junit-team/junit4/pull/1385

Is there a reason for this to be correct, but mine is not?

Thanks :+1:

**Comment by kcooney** [comment]
There are a few differences:

1. The previous code there did an explicit "new" on a primitive type, which
is usually not the right thing to do (Integer.valueOf() has a cache). The
code you are changing uses `valueOf()` which is what the compiler would do
when autoboxing a primative type.

2. ListTest is sample code, so having it do something that was clearly not
canonical Java is a bit embarrassing

3. The Assert class has some overloaded methods, so changes like these
might have unintended consequences.

Finally (and this is just my personal opinion) I don't like changes that
only update code from one code style to another. Generally the code in
JUnit was approved by at least one person, so two people agreed that the
style was reasonable.

if you want to make a larger impact, we have many issues labeled
"lowhanging" that you could work on. See
https://github.com/junit-team/junit4/issues?q=is%3Aissue+is%3Aopen+label%3Alowhanging

**Comment by Mathreyu** [comment]
Thanks for the clarification, I will try to contribute on the issues you recommended :)

**Comment by marcphilipp** [comment]
I'm with @kcooney on this one.

**Comment by kcooney** [comment]
FYI, I updated https://github.com/junit-team/junit4/blob/master/CONTRIBUTING.md to document this policy

**Pull request closed without merging**
