### PR TITLE
Replace for with foreach

### PR DESCRIPTION
**Pull request by renuka-fernando**
- Simplify `If` statements in `Double` and `Float` checking methods with of `Assert` class.

### CODE REVIEW

**Comment by kcooney** [comment]
Thanks for the contribution.

The changes to Assert take fewer lines, but I am not sure iI agree that the newer code is simpler. I could see replacing the second "if (something) { return false } return true" with "return inverted something". That being said, presumably the original author and reviewer(s) were happy with what was there...

**Comment by renuka-fernando** [comment]
Yes, I also felt it's easy to understand with if blocks.

**Comment by kcooney** [comment]
@renuka-fernando could you delete the first commit, keep the second commit (the "for-each" commit) and force-push the changes to GitHub?

**Comment by renuka-fernando** [comment]
@kcooney
I have deleted the first commit, thank you.

**Comment by kcooney** [comment]
@renuka-fernando thanks! Merged.

**Pull request merged**
