### PR TITLE
Deprecated since jdk9 replacing constructor instance of Double and Float

### PR DESCRIPTION
**Pull request by RahulNagekar**

### CODE REVIEW

**Comment by marcphilipp** [comment]
Can't we simply rely on autoboxing?

**Comment by RahulNagekar** [comment]
> Can't we simply rely on autoboxing?

Right, good point.

**Comment by kcooney** [comment]
@marcphilipp @RahulNagekar  I personally prefer not using autoboxing here. Having an explicit conversion here makes it clear to future readers that a conversion is happening.

**Comment by stefanbirkner** [comment]
I'm also in favour for Double.valueOf so that the code is the same like in JUnit 4's `Assert`.

**Comment by RahulNagekar** [comment]
I currently not sure if autoboxing would be more beneficial or valueOf (performance-wise).
As valueOf is used at many places in this file, I say keep it the same to preserve consistency in code.
:-)

**Pull request merged**
