### PR TITLE
Fix Travis build

### PR DESCRIPTION
**Pull request by stefanbirkner**
Travis switched from Ubuntu Precise images to Ubuntu Trusty images. The Trusty images don't have installed OpenJDK 6 by default. See travis-ci/travis-ci#8199. Furthermore Oracle JDK 7 is not available anymore. See travis-ci/travis-ci#7884.

### CODE REVIEW

**Comment by stefanbirkner** [comment]
The failing build shows that the installed Maven cannot be used with JDK6. I fix this after October, 15th.

**Comment by stefanbirkner** [comment]
The pull request is now ready to be merged.

**Comment by jxmai** [comment]
I closed https://github.com/junit-team/junit4/pull/1486 since this Pull can already fix most of the issue, but wouldn't it be nice to also include `openjdk8` in travis build ?

**Comment by stefanbirkner** [comment]
@marcphilipp The build is failing on Jenkins. Can you please have a look (and maybe let Jenkins use the Maven Wrapper, too).

**Comment by marcphilipp** [comment]
Jenkins is fixed. I created a completely new build that uses the Maven wrapper.

**Comment by stefanbirkner** [comment]
Thanks.

**Pull request merged**
