### PR TITLE
Fixed some grammatical mistakes in the comments in junit.framework

### PR DESCRIPTION
**Pull request by jhfjhfj1**

### CODE REVIEW

**Comment by stefanbirkner** [comment]
LGTM

**Comment by jhfjhfj1** [comment]
@marcphilipp Should this be merged?

**Comment by kcooney** [comment]
I suspect this wasn't merged because git didn't provide a good UI to squash commits. If the conflicts can be resolved, I'd be happy to merge it.

**Comment by PeterWippermann** [comment]
@jhfjhfj1 Maybe you can do a rebase to have the merge conflicts disappear? Don't let your effort go to waste :-)

**Comment by jhfjhfj1** [comment]
@kcooney @PeterWippermann Thank you guys!
I have solved the conflicts.

**Comment by PeterWippermann** [comment]
Well done! Congratulations @jhfjhfj1 👍 :-)

**Pull request merged**
