### PR TITLE
Run ErrorCollectorTest with Parameterized runner

### PR DESCRIPTION
**Pull request by stefanbirkner**
The array for the Parameterized gives a better overview of the tests.

### CODE REVIEW

**Comment by panchenko** [comment]
I agree it looks shorter, how convenient is this for debugging?

**Comment by stefanbirkner** [comment]
The debugging experience depends on the IDE. With IntelliJ it is possible to debug a single parameter set. I have no actual experience with other IDEs.

**Comment by marcphilipp** [comment]
Now the build seems to fail on JDK 5: https://junit.ci.cloudbees.com/job/JUnit/10/console

@stefanbirkner Can you please take a look?

**Comment by stefanbirkner** [comment]
I will have a look at it, but maybe not today.

**Pull request merged**
